// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float4> Input;
RWTexture2D<float4> Result;
int AlphaOn;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float grayscale = dot(Input[id.xy].xyz, float3(0.299, 0.587, 0.114));
    Result[id.xy] = float4(grayscale, grayscale, grayscale, 1);
}
